apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: back-end
          image: example
          ports:
            - containerPort: 9090